apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:	
    deployment.kubernetes.io/revision: '3'	
  generation: 4
  name: heathrecords-fhir-api-dev
  namespace: default
  labels:
    run: heathrecords-fhir-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: heathrecords-fhir-api-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        run: heathrecords-fhir-api-dev
    spec:
      containers:
        - name: heathrecords-fhir-api-dev
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: lock
              value: key
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: 128Mi
            limits:
              cpu: "100m"
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
