apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:	
    deployment.kubernetes.io/revision: '1'	
    kubectl.kubernetes.io/last-applied-configuration: >	
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"generation":1,"labels":{"run":"heathrecords-fhir-api-dev"},"name":"heathrecords-fhir-api-dev","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"heathrecords-fhir-api-dev"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"run":"heathrecords-fhir-api-dev"}},"spec":{"containers":[{"env":[{"name":"lock","value":"key"}],"image":"nginx:latest","imagePullPolicy":"Always","name":"heathrecords-fhir-api-dev","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"8Gi"},"requests":{"cpu":"100m","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/heathrecords-fhir-api-dev/config.properties","name":"config"},{"mountPath":"/application.yaml","name":"app-config","subPath":"application.yaml"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60,"volumes":[{"configMap":{"defaultMode":420,"name":"heathrecords-fhir-api-dev-configmap"},"name":"config"},{"configMap":{"defaultMode":420,"name":"hapi-config"},"name":"app-config"}]}}}}	
  generation: 1
  name: heathrecords-fhir-api-dev
  namespace: default
  labels:
    run: heathrecords-fhir-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: heathrecords-fhir-api-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        run: heathrecords-fhir-api-dev
    spec:
      containers:
        - name: heathrecords-fhir-api-dev
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: lock
              value: key
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: 128Mi
            limits:
              cpu: "100m"
              memory: 256Mi
          volumeMounts:
            - mountPath: /usr/heathrecords-fhir-api-dev/config.properties
              name: config
            - mountPath: /application.yaml
              name: app-config
              subPath: application.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: config
          configMap:
            name: heathrecords-fhir-api-dev-configmap
            defaultMode: 420
        - name: app-config
          configMap:
            name: hapi-config
            defaultMode: 420
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
