apiVersion: v1
kind: Service
metadata:
  name: heathrecords-fhir-api-dev
  namespace: default
  labels:
    run: heathrecords-fhir-api-dev
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    run: heathrecords-fhir-api-dev
  sessionAffinity: None
