apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    run: heathrecords-fhir-api-dev
  name: heathrecords-fhir-api-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: heathrecords-fhir-api-dev
  sessionAffinity: None
  type: LoadBalancer
