apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhp-background-synchronizer-dev
  namespace: default
  labels:
    app.kubernetes.io/name: dhp-background-synchronizer-dev
    app.kubernetes.io/instance: dhp-background-synchronizer-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: dhp-background-synchronizer-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhp-background-synchronizer-dev
    spec:
      containers:
      - name: dhp-background-synchronizer-dev
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /opt/app/synchronizer/config/secrets
          name: secret
      volumes:
      - name: secret
        secret:
          defaultMode: 420
          secretName: dhp-background-synchronizer-dev-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
