apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-30T17:50:11Z"
  generation: 1
  labels:
    run: device-integration-dev
  name: device-integration-dev
  namespace: default
  resourceVersion: '404006'	
  uid: 986eae62-e104-42bd-9e93-97f4c941cae2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: device-integration-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-10T12:11:46Z"
      creationTimestamp: null
      labels:
        run: device-integration-dev
    spec:
      containers:
      - env:
        - name: lock
          value: key
        image: nginx:latest #gcr.io/dhp-poc/device-integration:2024-11-27T10-17-39Z.989.1c53ae6b
        imagePullPolicy: Always
        name: device-integration-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi #5000Mi
          requests:
            cpu: 10m #100m
            memory: 50Mi #4000Mi
        # terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        # - mountPath: /usr/device-integration-dev/config.properties
        #   name: config
        - mountPath: /etc/device-integration-dev/secrets
          name: secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      # - configMap:
      #     defaultMode: 420
      #     name: device-integration-dev-configmap
      #   name: config
      # - name: secret
      #   secret:
      #     defaultMode: 420
      #     secretName: device-integration-dev-secret
status:
  availableReplicas: 1
  # conditions:
  # - lastTransitionTime: '2024-12-27T11:55:01Z'	
  #   lastUpdateTime: '2024-12-27T11:55:01Z'
  #   message: Deployment has minimum availability.
  #   reason: MinimumReplicasAvailable
  #   status: "True"
  #   type: Available
  # - lastTransitionTime: '2024-12-27T11:54:58Z'	
  #   lastUpdateTime: '2024-12-27T11:55:01Z'
  #   message: ReplicaSet "device-integration-dev-57d76bb6f9" has successfully
  #   reason: NewReplicaSetAvailable
  #   status: "True"
  #   type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1