apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-12-30T17:50:11Z","generation":1,"labels":{"app.kubernetes.io/instance":"device-integration-dev","run":"device-integration-dev"},"name":"device-integration-dev","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"device-integration-dev"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-09-10T12:11:46Z"},"creationTimestamp":null,"labels":{"run":"device-integration-dev"}},"spec":{"containers":[{"env":[{"name":"lock","value":"key"}],"image":"nginx:latest","imagePullPolicy":"Always","name":"device-integration-dev","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"500Mi"},"requests":{"cpu":"10m","memory":"50Mi"}},"terminationMessagePolicy":"File","volumeMounts":null}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60}}},"status":{"availableReplicas":1,"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-12-27T14:15:59Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: device-integration-dev
    run: device-integration-dev
  name: device-integration-dev
  namespace: default
  resourceVersion: "416194"
  uid: f305e421-f1b5-4c37-8811-fea9567e71c0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: device-integration-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-10T12:11:46Z"
      creationTimestamp: null
      labels:
        run: device-integration-dev
    spec:
      containers:
      - env:
        - name: lock
          value: key
        image: nginx:latest
        imagePullPolicy: Always
        name: device-integration-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-27T14:16:03Z"
    lastUpdateTime: "2024-12-27T14:16:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-27T14:15:59Z"
    lastUpdateTime: "2024-12-27T14:16:03Z"
    message: ReplicaSet "device-integration-dev-847b94c69f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1