apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app.kubernetes.io/instance: device-integration-dev
    run: device-integration-dev
  name: device-integration-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31121
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: device-integration-dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}