apiVersion: v1
kind: Service
metadata:
  name: device-integration-dev
  namespace: default
  labels:
    run: device-integration-dev
spec:
  ports:
  - nodePort: 31121
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: device-integration-dev
  type: NodePort
