apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # NodePort must be in the range 30000-32767
  type: NodePort
