apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-31T04:18:26Z"
  generation: 9
  labels:
    app.kubernetes.io/instance: heathrecords-fhir-wellness-api-dev
    run: heathrecords-fhir-wellness-api-dev
  name: heathrecords-fhir-wellness-api-dev
  namespace: default
  resourceVersion: '475898'	
  uid: fc239ba5-a8c6-4e6a-a963-cf84cf890970
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: heathrecords-fhir-wellness-api-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: heathrecords-fhir-wellness-api-dev
    spec:
      containers:
      - env:
        - name: lock
          value: key
        image: nginx:latest
        imagePullPolicy: Always
        name: heathrecords-fhir-wellness-api-dev
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
