apiVersion: v1
kind: Service
metadata:
  labels:
    run: messaging-dev
  name: messaging-dev
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: messaging-dev
  sessionAffinity: None
  type: ClusterIP
