apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/instance: synchronizer-dev
    run: synchronizer-dev
  name: synchronizer-dev
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: synchronizer-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: synchronizer-dev
    spec:
      containers:
        - env:
            - name: lock
              value: key
          image: nginx:latest
          imagePullPolicy: Always
          name: synchronizer-dev
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: 50Mi
            requests:
              cpu: "50m"
              memory: 30Mi
          terminationMessagePath: /dev/synchronizer-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
