apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "27"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-12-31T04:12:13Z","generation":1,"labels":{"run":"synchronizer-dev"},"name":"synchronizer-dev","namespace":"default","resourceVersion":"7425418","uid":"b66d1b34-974c-4d77-9e27-0c1ea0ddbc51"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"synchronizer-dev"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"synchronizer-dev"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_HTTPS_PORT","value":"443"},{"name":"Gateways__DestinationDstu2","value":"https://heathrecords-fhir-dstu2-allscripts-api-dev-47lzkehxga-uc.a.run.app"},{"name":"Gateways__DestinationStu3","value":"https://heathrecords-fhir-api-dev-47lzkehxga-uc.a.run.app"},{"name":"Gateways__DestinationR4","value":"https://heathrecords-fhir-api-dev-47lzkehxga-uc.a.run.app"},{"name":"Gateways__EpicDstu2","value":"https://fhir.epic.com/interconnect-fhir-oauth"},{"name":"Gateways__EpicStu3","value":"https://fhir.epic.com/interconnect-fhir-oauth"},{"name":"Gateways__EpicR4","value":"https://fhir.epic.com/interconnect-fhir-oauth"},{"name":"Gateways__AllscriptsDstu2","value":"https://tw181unityfhir.open.allscripts.com"},{"name":"Gateways__UserService","value":"https://user-service-dev-47lzkehxga-uc.a.run.app"},{"name":"Redis__Url","value":"10.90.81.3:6379"},{"name":"CreateDoctorUserWhenImporting","value":"false"}],"image":"gcr.io/dhp-poc/integration-services:211215.10.50ad1265","imagePullPolicy":"Always","name":"heathrecords-fhir-api-dev","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"1532Mi"},"requests":{"cpu":"500m"}},"terminationMessagePath":"/dev/synchronizer-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-12-31T04:12:36Z","lastUpdateTime":"2021-12-31T04:12:36Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-12-31T04:12:13Z","lastUpdateTime":"2021-12-31T04:12:36Z","message":"ReplicaSet \"synchronizer-dev\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-01-01T19:13:38Z"
  generation: 28
  labels:
    run: synchronizer-dev
  name: synchronizer-dev
  namespace: default
  resourceVersion: "747092893"
  uid: aa8795e5-7931-484b-a454-3b2ac0835a12
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: synchronizer-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-02-08T01:48:56Z"
      creationTimestamp: null
      labels:
        run: synchronizer-dev
    spec:
      containers:
      - env:
        - name: ASPNETCORE_HTTPS_PORT
          value: "443"
        - name: Gateways__DestinationDstu2
          value: http://heathrecords-fhir-api-dev.default.svc.cluster.local:80
        - name: Gateways__DestinationStu3
          value: http://heathrecords-fhir-api-dev.default.svc.cluster.local:80
        - name: Gateways__DestinationR4
          value: http://heathrecords-fhir-api-dev.default.svc.cluster.local:80
        - name: Gateways__EpicDstu2
          value: https://fhir.epic.com/interconnect-fhir-oauth
        - name: Gateways__EpicStu3
          value: https://fhir.epic.com/interconnect-fhir-oauth
        - name: Gateways__EpicR4
          value: https://fhir.epic.com/interconnect-fhir-oauth
        - name: Gateways__AllscriptsDstu2
          value: https://tw181unityfhir.open.allscripts.com
        - name: Gateways__UserService
          value: https://myhealth-api-dev.default.svc.cluster.local/userservice
        - name: Gateways__ColigomedEhrBaseUrl
          value: http://heathrecords-fhir-api-dev.default.svc.cluster.local:80
        - name: Gateways__FhirR4ConverterBaseUrl
          value: https://myhealth-api-dev.default.svc.cluster.local/fhirversionconverter
        - name: Redis__Url
          value: 10.90.81.3:6379
        - name: CreateDoctorUserWhenImporting
          value: "false"
        image: gcr.io/dhp-poc/integration-services:220402.49.612d845a
        imagePullPolicy: Always
        name: synchronizer-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/synchronizer-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/synchronizer-dev/config.properties
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: synchronizer-dev-configmap
        name: config
status:
  conditions:
  - lastTransitionTime: "2022-01-01T19:13:38Z"
    lastUpdateTime: "2023-01-31T16:56:44Z"
    message: ReplicaSet "synchronizer-dev-6b667c9c47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-03T04:11:43Z"
    lastUpdateTime: "2024-05-03T04:11:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 28