apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    run: synchronizer-dev
  name: synchronizer-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31559
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: synchronizer-dev
  sessionAffinity: None
  type: NodePort
