apiVersion: v1
data:
  DB_PASSWORD: N3UxVWpQOU1wNQo=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: hr-service-dev
  creationTimestamp: "2022-02-07T23:27:14Z"
  name: hr-service-dev-secret
  namespace: default
type: Opaque