apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    run: wellness-service-dev
  name: wellness-service-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30391
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: wellness-service-dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
