apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-11-07T05:13:56Z"
  generation: 2
  labels:
    app: presentation-service
    app.kubernetes.io/instance: presentation-service-dev
  name: presentation-service-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: presentation-service
    spec:
      containers:
      - env:
        - name: lock
          value: key
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: presentation-service-dev
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
