apiVersion: v1
kind: Service
metadata:
  name: presentation-service-dev
  namespace: default
spec:
  ports:
  - nodePort: 30017
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: presentation-service
  type: NodePort
