apiVersion: v1
kind: Service
metadata:
  name: dhp-background-synchronizer-dev
  namespace: default
  # annotations:
  #   cloud.google.com/neg: '{"ingress":true}'
spec:
  # clusterIP: 10.12.10.48
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31931
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: dhp-background-synchronizer-dev
  sessionAffinity: None
  type: NodePort
