apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1" # ArgoCD will update this on sync
  creationTimestamp: null # Allow Kubernetes to set this automatically
  generation: 1 # Automatically managed by Kubernetes
  labels:
    app.kubernetes.io/instance: file-services-dev
    run: file-services-dev
  name: file-services-dev
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: file-services-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: file-services-dev
    spec:
      containers:
      - env:
        - name: lock
          value: key
        image: nginx:latest  
        imagePullPolicy: Always
        name: file-services-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: 256Mi
          requests:
            cpu: "50m"
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
