apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-portal-dev
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: provider-portal-dev
  template:
    metadata:
      labels:
        run: provider-portal-dev
    spec:
      containers:
      - name: provider-portal-dev
        image: nginx:latest
        imagePullPolicy: Always
        env:
        - name: lock
          value: key
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
          protocol: TCP
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
