apiVersion: v1
kind: Service
metadata:
  name: provider-portal-dev
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32265
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: provider-portal-dev
  sessionAffinity: None
  type: NodePort
