apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-01T18:48:04Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: user-service-dev
    run: user-service-dev
  name: user-service-dev
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: user-service-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: user-service-dev
    spec:
      containers:
      - name: user-service
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: lock
          value: key
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
