apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    run: user-service-dev
  name: user-service-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30403
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: user-service-dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
