apiVersion: v1
data:
  CERNER_SECRET: ++++++++
  ECW_CLIENT_SECRET: ++++++++
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: user-service-dev
  creationTimestamp: "2022-02-08T05:50:00Z"
  name: user-service-dev-secret
  namespace: default
type: Opaque