apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}  # Removed revision and kubectl restart annotations
  labels:
    app.kubernetes.io/instance: fhir-integration-dev
    run: fhir-integration-dev
  name: fhir-integration-dev
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: fhir-integration-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: fhir-integration-dev
    spec:
      containers:
      - env:
        - name: lock
          value: key  # Only this env variable remains
        image: nginx:latest  # Updated image to nginx:latest
        imagePullPolicy: Always
        name: fhir-integration-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: 256Mi
          requests:
            cpu: "50m"
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: fhir-integration-dev-configmap
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: '2024-12-29T22:13:53Z'	
    lastUpdateTime: '2024-12-29T22:13:53Z'
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: '2024-12-29T22:13:49Z'	
    lastUpdateTime: '2024-12-29T22:13:53Z'	
    message: ReplicaSet "fhir-integration-dev-98d84bd89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
