apiVersion: v1
kind: Service
metadata:
  annotations: {}  # Removed unnecessary annotations
  labels:
    run: fhir-integration-dev
  name: fhir-integration-dev
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: fhir-integration-dev
  sessionAffinity: None
  type: LoadBalancer  
status:
  loadBalancer: {}  
